### ISSUE TITLE
Needs to be re-enabled at each login?

### ISSUE THREAD

**Issue by abhijit86k** [romeshell/windows-alt-tab#8]
Each time I login, the behaviour goes to the old state - Alt - tab shows all running applications. After re-enabling the addon in gnome-tweak-tool it starts working fine again - till the next time i log in.
~Abhijit
Debian Wheezy with all updates

**Comment by tglman** [comment]
I'm using debian sid and it work well, can you try to capture same log when the extension start, and which other extension are you using??

**Comment by abhijit86k** [comment]
I tried disabling all other extentions and re-enabling one by one - turns out it conflicts with an addon called "AlternateTabExtention". Have disabled that and this one works fine now.
